name: outrigger-env
channels:
  - conda-forge
  - r
  - bioconda
dependencies:
- python=3
- pytest
- pandas>=0.17.0
- flake8
- coverage
- gffutils
- pybedtools
- biopython
- bedtools
- joblib
- pysam
- sphinx>=1.3.6
- sphinx_rtd_theme
- pip:
    - graphlite
    - pyflakes
    - recommonmark==0.4.0
    - nbsphinx
